alias python="python3"
alias pip="pip3"
alias vi="/snap/nvim/current/usr/bin/nvim"
alias vim="/snap/nvim/current/usr/bin/nvim"
alias l.="ls -d .* --color=auto"
alias ..="cd .."
#alias apt_update_all= "sudo apt update && sudo apt upgrade;"
countjson() { grep -o "{" "$1" | wc -l; }
ssh_remember() { eval `ssh-agent`;  ssh-add;}

